---
- hosts: Firewalls
  gather_facts: no
  connection: local
  vars_files:
  - ios.yml
  - firewall.yml
#  - VLANS.yml
  tasks:
  - name: Define connection
    set_fact:
      connection:
        authorize: yes
        username: "{{ ANSIBLE_NET_USERNAME }}"
        password: "{{ ANSIBLE_NET_PASS }}"
        auth_pass: "{{ ANSIBLE_NET_AUTH_PASS }}"

#  - name: Generate configs for each device
#    template:
#      src: "./jinjavlan.j2"
#      dest: "./configs/{{inventory_hostname}}.cfg"

#Below is just VLAN configuration
  - name: Generate configs for each device
    template:
      src: "./ASAJinja.j2"
      dest: "./configs/{{inventory_hostname}}.cfg"

  - name: Pushing the configs created using JinjaAndYAML
    asa_config:
      src: "./configs/{{inventory_hostname}}.cfg"
      provider: "{{ connection }}"





#  - name: Setting up OSPF Passive Interfaces
#    ios_config:
#      lines: 
#      - passive-interface {{item[0]}}
#      parents:
#      - router ospf 1
#      provider: "{{ connection }}"
#    when:
#      - item[1].passiveinterface is defined 
#      - item[1].passiveinterface == True 
#    with_items:
#      - "{{nodes[inventory_hostname].links.items()}}"
    
