---
- hosts: Routers:Switches
  gather_facts: no
  connection: local
  vars_files:
  - ios.yml
  tasks:
  - name: Define connection
    set_fact:
      connection:
        authorize: yes
        username: "{{ ANSIBLE_NET_USERNAME }}"
        password: "{{ ANSIBLE_NET_PASS }}"
        auth_pass: "{{ ANSIBLE_NET_AUTH_PASS }}"


  - name: Setting up CDP data file for Diagram usage
    ios_command:
      commands: show cdp neighbors | begin Device ID
      provider: "{{ connection }}"
    register: showinformation
  - name: Save output to local folder for pythonscript
    copy:
      content: "{{showinformation.stdout[0]}}"
      dest: "CDP/{{inventory_hostname}}_show_CDP.txt"

  - name: Running script to create a network diagram
    debug: msg="{{ lookup('pipe', './PythonDiagram.py')}}"
    run_once: true

